#!/usr/bin/env python3
"""mine_transcripts.py — scan Claude Code transcripts for recurring user-correction patterns.

Implements Eugene Yan's "close the loop" practice (How to Work and Compound with AI, 2026-05):
read recent conversation transcripts, count corrections that share patterns, surface the top
ones so they can be promoted into CLAUDE.md / skills / memory files.

Default scope: ~/.claude/projects/*/*.jsonl, last 14 days, all categories.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

DEFAULT_PATTERNS_PATH = Path(__file__).parent / "patterns.json"


def encode_cwd_as_project(cwd: Path) -> str:
    """Claude Code encodes /a/b/c → -a-b-c for the project directory name."""
    abs_path = str(cwd.resolve())
    return abs_path.replace("/", "-")


def load_patterns(path: Path) -> dict:
    with path.open() as f:
        return json.load(f)


def find_transcripts(claude_dir: Path, since: datetime, project_filter: str | None = None) -> list[Path]:
    proj_dir = claude_dir / "projects"
    if not proj_dir.exists():
        return []
    transcripts = []
    for jsonl in proj_dir.rglob("*.jsonl"):
        try:
            mtime = datetime.fromtimestamp(jsonl.stat().st_mtime, tz=timezone.utc)
        except OSError:
            continue
        if mtime < since:
            continue
        if project_filter and project_filter not in str(jsonl):
            continue
        transcripts.append(jsonl)
    return sorted(transcripts)


# Markers that indicate the message is system-generated, not user-typed.
# If any of these appear anywhere in the message, the entire message is skipped.
NOISE_MARKERS = (
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<system-reminder>",
    "<task-notification>",
    "<task-id>",
    "<tool-use-id>",
    "<output-file>",
    "<user-prompt-submit-hook>",
    "Caveat: The messages below were generated by the user",
    "UserPromptSubmit hook",
    "SessionStart:clear hook",
)


def extract_user_text(obj: dict) -> str | None:
    """Return the actual user-typed text from a transcript entry, or None to skip."""
    if obj.get("type") != "user":
        return None
    if obj.get("isMeta"):
        return None
    msg = obj.get("message")
    if not isinstance(msg, dict):
        return None
    if msg.get("role") != "user":
        return None
    content = msg.get("content")
    if isinstance(content, list):
        # tool_result blocks etc — skip
        return None
    if not isinstance(content, str):
        return None
    text = content.strip()
    if len(text) < 5:
        return None
    if any(marker in text for marker in NOISE_MARKERS):
        return None
    return text


def parse_jsonl(path: Path):
    """Yield (timestamp_str, text, project_name) for real user messages."""
    project = path.parent.name
    try:
        with path.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue
                text = extract_user_text(obj)
                if text is None:
                    continue
                ts = obj.get("timestamp", "")
                yield ts, text, project, obj.get("sessionId", "")
    except IOError:
        return


def compile_patterns(patterns_data: dict) -> dict:
    compiled = {}
    for name, body in patterns_data.items():
        regexes = body.get("regexes", []) if isinstance(body, dict) else body
        compiled[name] = [re.compile(r, re.IGNORECASE | re.MULTILINE) for r in regexes]
    return compiled


def match_categories(text: str, compiled: dict) -> list[str]:
    hits = []
    for name, regexes in compiled.items():
        for regex in regexes:
            if regex.search(text):
                hits.append(name)
                break
    return hits


def truncate(text: str, n: int = 280) -> str:
    text = " ".join(text.split())
    if len(text) <= n:
        return text
    return text[: n - 1] + "…"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Scan Claude Code transcripts for recurring correction patterns."
    )
    parser.add_argument("--days", type=int, default=14, help="lookback window in days (default 14)")
    parser.add_argument(
        "--claude-dir",
        type=Path,
        default=Path.home() / ".claude",
        help="Claude config directory (default ~/.claude)",
    )
    parser.add_argument(
        "--patterns",
        type=Path,
        default=DEFAULT_PATTERNS_PATH,
        help="path to patterns.json (default: bundled)",
    )
    parser.add_argument(
        "--project",
        default=None,
        help="filter to transcripts whose path contains this substring (overrides default of current-project-only)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="scan all projects (overrides default of current-project-only)",
    )
    parser.add_argument(
        "--cwd",
        type=Path,
        default=None,
        help="treat this path as the current working directory for project detection (default: actual CWD)",
    )
    parser.add_argument("--limit", type=int, default=20, help="max examples per category")
    parser.add_argument(
        "--min-hits",
        type=int,
        default=3,
        help="suppress categories below this threshold (default 3)",
    )
    args = parser.parse_args()

    if not args.patterns.exists():
        print(f"patterns file not found: {args.patterns}", file=sys.stderr)
        return 1

    patterns_data = load_patterns(args.patterns)
    compiled = compile_patterns(patterns_data)

    since = datetime.now(timezone.utc) - timedelta(days=args.days)

    # Scope resolution: explicit --project or --all wins; otherwise default to CWD-derived project.
    if args.all:
        project_filter = None
        scope_label = "all projects"
    elif args.project:
        project_filter = args.project
        scope_label = f"project filter: '{args.project}'"
    else:
        cwd = args.cwd if args.cwd else Path.cwd()
        project_filter = encode_cwd_as_project(cwd)
        scope_label = f"current project: {cwd} → {project_filter}"

    transcripts = find_transcripts(args.claude_dir, since, project_filter)

    if not transcripts:
        print(
            json.dumps(
                {
                    "scope": scope_label,
                    "transcripts_scanned": 0,
                    "note": "no transcripts in window for this scope. Use --all for cross-project pass.",
                },
                indent=2,
            )
        )
        return 0

    counts = Counter()
    examples = defaultdict(list)
    by_project = defaultdict(Counter)
    sessions_with_hits = defaultdict(set)
    user_messages_seen = 0

    for jsonl in transcripts:
        for ts, text, project, session_id in parse_jsonl(jsonl):
            user_messages_seen += 1
            hits = match_categories(text, compiled)
            for name in hits:
                counts[name] += 1
                by_project[project][name] += 1
                sessions_with_hits[name].add(session_id)
                if len(examples[name]) < args.limit:
                    examples[name].append(
                        {
                            "timestamp": ts,
                            "project": project,
                            "session": session_id[:8] if session_id else "",
                            "snippet": truncate(text),
                        }
                    )

    # Filter categories below min-hits
    filtered_counts = Counter({k: v for k, v in counts.items() if v >= args.min_hits})

    output = {
        "scope": scope_label,
        "since": since.isoformat(),
        "lookback_days": args.days,
        "transcripts_scanned": len(transcripts),
        "user_messages_seen": user_messages_seen,
        "min_hits_threshold": args.min_hits,
        "category_descriptions": {
            name: body.get("description", "") if isinstance(body, dict) else ""
            for name, body in patterns_data.items()
        },
        "counts_by_category": dict(filtered_counts.most_common()),
        "sessions_per_category": {
            k: len(sessions_with_hits[k]) for k in filtered_counts
        },
        "counts_by_project": {
            p: dict(c.most_common()) for p, c in by_project.items() if any(c.values())
        },
        "examples": {k: examples[k] for k in filtered_counts},
        "suppressed_low_hits": {
            k: v for k, v in counts.items() if v < args.min_hits
        },
    }
    print(json.dumps(output, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
